### ISSUE TITLE
Can't enable events

### ISSUE THREAD

**Issue by pbalogh** [howdyai/botkit-starter-slack#38]
The Slack API settings require me to put in a Request URL for events to be enabled. I was under the impression that this would be the same as the botkit-starter-slack node app -- e.g., http://localhost:3000. (The Slack API settings require me to append /slack/receive to the end of the URL). However, the Slack API settings are testing that URL by POSTing a request to it and it is failing. Your tutorial/config shows a Glitch URL, but doesn't indicate at any point that Glitch is required or why it should be required, and I don't understand the use of the node app I'm running at localhost:3000 if it isn't able to process Events. Please clarify.

**Comment by benbrown** [comment]
Once you have your app running locally, you need to use a tool like ngrok or localtunnel to make it accessible on the public internet so that Slack can reach it.

The complexity and brittleness of this kind of setup is why have made the Glitch remix path the default/primary path for most people who are getting started -- Glitch offers a stable, SSL-enabled url for free.
